language: shell

git:
  depth: false

script:
  - bash scripts/generate.sh

deploy:
  provider: script
  script:
  - bash scripts/publish.sh "bash scripts/generate.sh"
  on:
    branch: develop

notifications:
  email: false
